---

# Minio binaries path
minio_server_bin: /usr/local/bin/minio
minio_client_bin: /usr/local/bin/mc

# Minio release to install. default if lastet
minio_server_release: "RELEASE.2021-05-26T00-22-46Z"
minio_client_release: ""

# Runtime user and group for the Minio server service
minio_user: minio
minio_group: minio

# Path to the file containing the ENV variables for the Minio server
minio_server_envfile: /etc/default/minio

# Minio server listen address
minio_server_addr: ":9091"

# Minio server data directories
minio_server_datadirs:
  - /minio-data
minio_server_make_datadirs: true

# Minio server cluster node list.
minio_server_cluster_nodes:
  - 'http://LMO-PROD-MINIO-1:9091/minio-data'
  - 'http://LMO-PROD-MINIO-2:9091/minio-data'
  - 'http://LMO-PROD-MINIO-3:9091/minio-data'
  - 'http://LMO-PROD-MINIO-4:9091/minio-data'
# Additional environment variables to be set in minio server environment
minio_server_env_extra: ""

# Additional Minio server CLI options
minio_server_opts: ""

# Minio access and secret keys
minio_access_key: "admin"
minio_secret_key: "P@ssminio"

# Switches to enable/disable the Minio server and/or Minio client installation.
minio_install_server: true
minio_install_client: false
