---
  - name: Download node-exporter
    unarchive:
      src: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
      dest: /tmp/
      remote_src: yes

  - name: Copy file with owner and permission, using symbolic representation
    ansible.builtin.copy:
      src: /tmp/node_exporter-1.0.1.linux-amd64/node_exporter
      dest: /usr/local/bin
      mode: '0755'
      remote_src: yes

  - name: Add the user 'node_exporter'
    user:
      name: node_exporter
      shell: /bin/false
      create_home: no

  - name: create node_exporter service file
    copy:
      src: node_exporter.service
      dest: /etc/systemd/system/node_exporter.service

  - name: Just force systemd to reread configs (2.4 and above)
    systemd:
      name: node_exporter.service
      daemon_reload: yes
      enabled: yes
      state: started
